baseURL = "https://seyednavidhashemi.github.io/NavSite/"
languageCode = "en"
title = "Navid Hashemi"
theme = "blowfish"

# منوهای بالای سایت
[[menu.main]]
  identifier = "posts"
  name = "Thoughts" # اسامی را کمی هنری‌تر کردیم
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "projects"
  name = "Showcase"
  url = "/projects/"
  weight = 20

[[menu.main]]
  identifier = "til"
  name = "TIL"
  url = "/til/"
  weight = 30

[params]
  defaultAppearance = "dark" # تاریکِ مطلق
  colorScheme = "neon" 

  [params.header]
    layout = "fixed" 

  [params.homepage]
    layout = "hero" # تغییر از پروفایل ساده به نمای سینمایی (Hero)
    showRecent = true
    cardView = true # نمایش تمام مطالب به صورت کارت‌های سه‌بعدی

  [params.ui]
    blur = true # جادوی اصلی: فعال‌سازی افکت شیشه‌ای (Glassmorphism)
    scrollspy = true

  [params.article]
    showReadingTime = true
    showViews = true

  [params.author]
    name = "Navid"
    image = "https://github.com/SeyedNavidHashemi.png"
    headline = "Building things for the web and beyond."
    links = [
      { github = "https://github.com/SeyedNavidHashemi" },
      { email = "mailto:navid.hashemi@ut.ac.ir" },
      { linkedin = "https://linkedin.com/in/seyed-navid-hashemi-485485395" }
    ]