baseURL = "https://seyednavidhashemi.github.io/NavSite/"
languageCode = "fa"
title = "Navid Hashemi Weblog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowToc = true

[params.profileMode]
  enabled = true
  title = "Hola! I'm Navid Hashemi 👋"
  subtitle = "Computer Engineering Student | Interested in Building and Learning."

  imageUrl = ""C:\Users\USER\Downloads\portrait.jpg"" 
  imageWidth = 120
  imageHeight = 120

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/SeyedNavidHashemi"

[[params.socialIcons]]
  name = "email"
  url = "mailto:navide.hashemi1383@gmail.com" 

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/seyed-navid-hashemi-485485395"
