baseURL = "https://seyednavidhashemi.github.io/NavSite/"
languageCode = "en"
title = "Navid Hashemi"
theme = "blowfish"

[[menu.main]]
  identifier = "posts"
  name = "Thoughts" 
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "projects"
  name = "Showcase"
  url = "/projects/"
  weight = 20

[[menu.main]]
  identifier = "til"
  name = "TIL"
  url = "/til/"
  weight = 30

[[menu.main]]
  identifier = "resume"
  name = "Resume"
  url = "/docs/resume.pdf"
  weight = 40
  
[params]
  defaultAppearance = "dark" 
  colorScheme = "neon" 

  [params.header]
    layout = "fixed" 

  [params.homepage]
    layout = "hero" 
    showRecent = true
    cardView = true  

  [params.ui]
    blur = true 
    scrollspy = true

  [params.article]
    showReadingTime = true
    showViews = true

  [params.author]
    name = "Navid"
    image = "https://github.com/SeyedNavidHashemi.png"
    headline = "Building things for the web and beyond."
    links = [
      { github = "https://github.com/SeyedNavidHashemi" },
      { email = "mailto:navid.hashemi@ut.ac.ir" },
      { linkedin = "https://linkedin.com/in/seyed-navid-hashemi-485485395" },
      { "file-pdf" = "/docs/resume.pdf" }
    ]